using System;
namespace generator
{
    public partial class Decoder
    {
        public Action NOP() => () => { };
        public Action LD((WideRegister, bool) p0, (DMGInteger, bool) p1) => () => { };
        public Action LD((WideRegister, bool) p0, (Register, bool) p1) => () => { };
        public Action INC((WideRegister, bool) p0) => () => { };
        public Action INC((Register, bool) p0) => () => { };
        public Action DEC((Register, bool) p0) => () => { };
        public Action LD((Register, bool) p0, (DMGInteger, bool) p1) => () => { };
        public Action RLCA() => () => { };
        public Action LD((DMGInteger, bool) p0, (WideRegister, bool) p1) => () => { };
        public Action ADD((WideRegister, bool) p0, (WideRegister, bool) p1) => () => { };
        public Action LD((Register, bool) p0, (WideRegister, bool) p1) => () => { };
        public Action DEC((WideRegister, bool) p0) => () => { };
        public Action RRCA() => () => { };
        public Action STOP() => () => { };
        public Action RLA() => () => { };
        public Action JR((DMGInteger, bool) p0) => () => { };
        public Action RRA() => () => { };
        public Action JR((Flag, bool) p0, (DMGInteger, bool) p1) => () => { };
        public Action DAA() => () => { };
        public Action CPL() => () => { };
        public Action SCF() => () => { };
        public Action CCF() => () => { };
        public Action LD((Register, bool) p0, (Register, bool) p1) => () => { };
        public Action HALT() => () => { };
        public Action ADD((Register, bool) p0, (Register, bool) p1) => () => { };
        public Action ADD((Register, bool) p0, (WideRegister, bool) p1) => () => { };
        public Action ADC((Register, bool) p0, (Register, bool) p1) => () => { };
        public Action ADC((Register, bool) p0, (WideRegister, bool) p1) => () => { };
        public Action SUB((Register, bool) p0) => () => { };
        public Action SUB((WideRegister, bool) p0) => () => { };
        public Action SBC((Register, bool) p0, (Register, bool) p1) => () => { };
        public Action SBC((Register, bool) p0, (WideRegister, bool) p1) => () => { };
        public Action AND((Register, bool) p0) => () => { };
        public Action AND((WideRegister, bool) p0) => () => { };
        public Action XOR((Register, bool) p0) => () => { };
        public Action XOR((WideRegister, bool) p0) => () => { };
        public Action OR((Register, bool) p0) => () => { };
        public Action OR((WideRegister, bool) p0) => () => { };
        public Action CP((Register, bool) p0) => () => { };
        public Action CP((WideRegister, bool) p0) => () => { };
        public Action RET((Flag, bool) p0) => () => { };
        public Action POP((WideRegister, bool) p0) => () => { };
        public Action JP((Flag, bool) p0, (DMGInteger, bool) p1) => () => { };
        public Action JP((DMGInteger, bool) p0) => () => { };
        public Action CALL((Flag, bool) p0, (DMGInteger, bool) p1) => () => { };
        public Action PUSH((WideRegister, bool) p0) => () => { };
        public Action ADD((Register, bool) p0, (DMGInteger, bool) p1) => () => { };
        public Action RST((byte, bool) p0) => () => { };
        public Action RET() => () => { };
        public Action PREFIX() => () => { };
        public Action CALL((DMGInteger, bool) p0) => () => { };
        public Action ADC((Register, bool) p0, (DMGInteger, bool) p1) => () => { };
        public Action ILLEGAL_D3() => () => { };
        public Action SUB((DMGInteger, bool) p0) => () => { };
        public Action RETI() => () => { };
        public Action ILLEGAL_DB() => () => { };
        public Action ILLEGAL_DD() => () => { };
        public Action SBC((Register, bool) p0, (DMGInteger, bool) p1) => () => { };
        public Action LDH((DMGInteger, bool) p0, (Register, bool) p1) => () => { };
        public Action ILLEGAL_E3() => () => { };
        public Action ILLEGAL_E4() => () => { };
        public Action AND((DMGInteger, bool) p0) => () => { };
        public Action ADD((WideRegister, bool) p0, (DMGInteger, bool) p1) => () => { };
        public Action JP((WideRegister, bool) p0) => () => { };
        public Action LD((DMGInteger, bool) p0, (Register, bool) p1) => () => { };
        public Action ILLEGAL_EB() => () => { };
        public Action ILLEGAL_EC() => () => { };
        public Action ILLEGAL_ED() => () => { };
        public Action XOR((DMGInteger, bool) p0) => () => { };
        public Action LDH((Register, bool) p0, (DMGInteger, bool) p1) => () => { };
        public Action DI() => () => { };
        public Action ILLEGAL_F4() => () => { };
        public Action OR((DMGInteger, bool) p0) => () => { };
        public Action LD((WideRegister, bool) p0, (WideRegister, bool) p1) => () => { };
        public Action EI() => () => { };
        public Action ILLEGAL_FC() => () => { };
        public Action ILLEGAL_FD() => () => { };
        public Action CP((DMGInteger, bool) p0) => () => { };
        public Action RLC((Register, bool) p0) => () => { };
        public Action RLC((WideRegister, bool) p0) => () => { };
        public Action RRC((Register, bool) p0) => () => { };
        public Action RRC((WideRegister, bool) p0) => () => { };
        public Action RL((Register, bool) p0) => () => { };
        public Action RL((WideRegister, bool) p0) => () => { };
        public Action RR((Register, bool) p0) => () => { };
        public Action RR((WideRegister, bool) p0) => () => { };
        public Action SLA((Register, bool) p0) => () => { };
        public Action SLA((WideRegister, bool) p0) => () => { };
        public Action SRA((Register, bool) p0) => () => { };
        public Action SRA((WideRegister, bool) p0) => () => { };
        public Action SWAP((Register, bool) p0) => () => { };
        public Action SWAP((WideRegister, bool) p0) => () => { };
        public Action SRL((Register, bool) p0) => () => { };
        public Action SRL((WideRegister, bool) p0) => () => { };
        public Action BIT((byte, bool) p0, (Register, bool) p1) => () => { };
        public Action BIT((byte, bool) p0, (WideRegister, bool) p1) => () => { };
        public Action RES((byte, bool) p0, (Register, bool) p1) => () => { };
        public Action RES((byte, bool) p0, (WideRegister, bool) p1) => () => { };
        public Action SET((byte, bool) p0, (Register, bool) p1) => () => { };
        public Action SET((byte, bool) p0, (WideRegister, bool) p1) => () => { };


    }
}