using NUnit.Framework;

namespace Tests;

internal class GBMicroTests
{
    [TestCase("cpu_bus_1")]
    [TestCase("dma_timing_a")]
    [TestCase("halt_bug")]
    [TestCase("halt_op_dupe_delay")]
    [TestCase("hblank_int_di_timing_a")]
    [TestCase("hblank_int_di_timing_b")]
    [TestCase("hblank_int_if_a")]
    [TestCase("hblank_int_l0")]
    [TestCase("hblank_int_scx0_if_a")]
    [TestCase("hblank_int_scx0_if_b")]
    [TestCase("hblank_int_scx0_if_c")]
    [TestCase("hblank_int_scx1")]
    [TestCase("hblank_int_scx1_if_a")]
    [TestCase("hblank_int_scx1_if_b")]
    [TestCase("hblank_int_scx1_if_c")]
    [TestCase("hblank_int_scx1_nops_b")]
    [TestCase("hblank_int_scx2")]
    [TestCase("hblank_int_scx2_if_a")]
    [TestCase("hblank_int_scx2_if_b")]
    [TestCase("hblank_int_scx2_if_c")]
    [TestCase("hblank_int_scx2_nops_b")]
    [TestCase("hblank_int_scx3")]
    [TestCase("hblank_int_scx3_if_a")]
    [TestCase("hblank_int_scx3_if_b")]
    [TestCase("hblank_int_scx3_if_c")]
    [TestCase("hblank_int_scx3_nops_b")]
    [TestCase("hblank_int_scx4_if_a")]
    [TestCase("hblank_int_scx4_if_b")]
    [TestCase("hblank_int_scx4_if_c")]
    [TestCase("hblank_int_scx4_nops_b")]
    [TestCase("hblank_int_scx5")]
    [TestCase("hblank_int_scx5_if_a")]
    [TestCase("hblank_int_scx5_if_b")]
    [TestCase("hblank_int_scx5_if_c")]
    [TestCase("hblank_int_scx5_nops_b")]
    [TestCase("hblank_int_scx6")]
    [TestCase("hblank_int_scx6_if_a")]
    [TestCase("hblank_int_scx6_if_b")]
    [TestCase("hblank_int_scx6_if_c")]
    [TestCase("hblank_int_scx6_nops_b")]
    [TestCase("hblank_int_scx7_if_a")]
    [TestCase("hblank_int_scx7_if_b")]
    [TestCase("hblank_int_scx7_if_c")]
    [TestCase("hblank_int_scx7_nops_b")]
    [TestCase("hblank_scx2_if_a")]
    [TestCase("hblank_scx3_if_a")]
    [TestCase("hblank_scx3_int_a")]
    [TestCase("hblank_scx3_int_b")]
    [TestCase("int_hblank_halt_bug_a")]
    [TestCase("int_hblank_halt_bug_b")]
    [TestCase("int_hblank_halt_scx0")]
    [TestCase("int_hblank_halt_scx1")]
    [TestCase("int_hblank_halt_scx2")]
    [TestCase("int_hblank_halt_scx3")]
    [TestCase("int_hblank_halt_scx4")]
    [TestCase("int_hblank_halt_scx5")]
    [TestCase("int_hblank_halt_scx6")]
    [TestCase("int_hblank_halt_scx7")]
    [TestCase("int_hblank_incs_scx0")]
    [TestCase("int_hblank_incs_scx1")]
    [TestCase("int_hblank_incs_scx2")]
    [TestCase("int_hblank_incs_scx3")]
    [TestCase("int_hblank_incs_scx4")]
    [TestCase("int_hblank_incs_scx5")]
    [TestCase("int_hblank_incs_scx6")]
    [TestCase("int_hblank_incs_scx7")]
    [TestCase("int_hblank_nops_scx0")]
    [TestCase("int_hblank_nops_scx1")]
    [TestCase("int_hblank_nops_scx2")]
    [TestCase("int_hblank_nops_scx3")]
    [TestCase("int_hblank_nops_scx4")]
    [TestCase("int_hblank_nops_scx5")]
    [TestCase("int_hblank_nops_scx6")]
    [TestCase("int_hblank_nops_scx7")]
    [TestCase("int_lyc_halt")]
    [TestCase("int_lyc_incs")]
    [TestCase("int_lyc_nops")]
    [TestCase("int_oam_halt")]
    [TestCase("int_oam_incs")]
    [TestCase("int_oam_nops")]
    [TestCase("int_timer_halt")]
    [TestCase("int_timer_halt_div_b")]
    [TestCase("int_vblank1_halt")]
    [TestCase("int_vblank1_incs")]
    [TestCase("int_vblank1_nops")]
    [TestCase("int_vblank2_halt")]
    [TestCase("int_vblank2_incs")]
    [TestCase("int_vblank2_nops")]
    [TestCase("lcdon_halt_to_vblank_int_a")]
    [TestCase("lcdon_halt_to_vblank_int_b")]
    [TestCase("lcdon_nops_to_vblank_int_b")]
    [TestCase("lcdon_to_if_oam_a")]
    [TestCase("lcdon_to_lyc1_int")]
    [TestCase("lcdon_to_lyc2_int")]
    [TestCase("lcdon_to_lyc3_int")]
    [TestCase("lcdon_to_oam_int_l0")]
    [TestCase("lcdon_to_oam_unlock_a")]
    [TestCase("lcdon_to_oam_unlock_c")]
    [TestCase("lcdon_to_stat0_a")]
    [TestCase("lcdon_to_stat0_c")]
    [TestCase("lcdon_to_stat0_d")]
    [TestCase("lcdon_to_stat1_a")]
    [TestCase("lcdon_to_stat1_b")]
    [TestCase("lcdon_to_stat1_d")]
    [TestCase("lcdon_to_stat2_a")]
    [TestCase("lcdon_to_stat2_b")]
    [TestCase("lcdon_to_stat2_c")]
    [TestCase("lcdon_to_stat2_d")]
    [TestCase("lcdon_to_stat3_a")]
    [TestCase("lcdon_to_stat3_c")]
    [TestCase("lcdon_to_stat3_d")]
    [TestCase("line_144_oam_int_c")]
    [TestCase("line_153_lyc0_int_inc_sled")]
    [TestCase("line_153_lyc0_stat_timing_a")]
    [TestCase("line_153_lyc0_stat_timing_b")]
    [TestCase("line_153_lyc0_stat_timing_c")]
    [TestCase("line_153_lyc0_stat_timing_f")]
    [TestCase("line_153_lyc0_stat_timing_h")]
    [TestCase("line_153_lyc0_stat_timing_j")]
    [TestCase("line_153_lyc0_stat_timing_m")]
    [TestCase("line_153_lyc0_stat_timing_n")]
    [TestCase("line_153_lyc153_stat_timing_a")]
    [TestCase("line_153_lyc153_stat_timing_c")]
    [TestCase("line_153_lyc153_stat_timing_d")]
    [TestCase("line_153_lyc153_stat_timing_e")]
    [TestCase("line_153_lyc153_stat_timing_f")]
    [TestCase("line_153_lyc_a")]
    [TestCase("line_153_lyc_c")]
    [TestCase("line_153_lyc_int_a")]
    [TestCase("line_153_lyc_int_b")]
    [TestCase("line_153_ly_c")]
    [TestCase("line_153_ly_d")]
    [TestCase("line_65_ly")]
    [TestCase("lyc1_int_halt_b")]
    [TestCase("lyc1_int_if_edge_a")]
    [TestCase("lyc1_int_if_edge_c")]
    [TestCase("lyc1_int_nops_b")]
    [TestCase("lyc1_write_timing_a")]
    [TestCase("lyc1_write_timing_b")]
    [TestCase("lyc1_write_timing_c")]
    [TestCase("lyc2_int_halt_b")]
    [TestCase("lyc_int_halt_b")]
    [TestCase("oam_int_halt_b")]
    [TestCase("oam_int_if_level_c")]
    [TestCase("oam_read_l0_a")]
    [TestCase("oam_read_l0_c")]
    [TestCase("oam_write_l0_a")]
    [TestCase("oam_write_l0_c")]
    [TestCase("oam_write_l0_e")]
    [TestCase("oam_write_l1_c")]
    [TestCase("poweron_div_000")]
    [TestCase("poweron_div_004")]
    [TestCase("poweron_div_005")]
    [TestCase("poweron_dma_000")]
    [TestCase("poweron_ly_000")]
    [TestCase("poweron_ly_119")]
    [TestCase("poweron_ly_120")]
    [TestCase("poweron_ly_233")]
    [TestCase("poweron_ly_234")]
    [TestCase("poweron_oam_000")]
    [TestCase("poweron_oam_005")]
    [TestCase("poweron_oam_006")]
    [TestCase("poweron_oam_069")]
    [TestCase("poweron_oam_070")]
    [TestCase("poweron_oam_183")]
    [TestCase("poweron_oam_184")]
    [TestCase("poweron_sb_000")]
    [TestCase("poweron_sc_000")]
    [TestCase("poweron_stat_000")]
    [TestCase("poweron_stat_005")]
    [TestCase("poweron_stat_006")]
    [TestCase("poweron_stat_007")]
    [TestCase("poweron_stat_026")]
    [TestCase("poweron_stat_027")]
    [TestCase("poweron_stat_069")]
    [TestCase("poweron_stat_070")]
    [TestCase("poweron_stat_119")]
    [TestCase("poweron_stat_120")]
    [TestCase("poweron_stat_140")]
    [TestCase("poweron_stat_183")]
    [TestCase("poweron_stat_234")]
    [TestCase("poweron_tima_000")]
    [TestCase("poweron_vram_000")]
    [TestCase("poweron_vram_069")]
    [TestCase("poweron_vram_070")]
    [TestCase("poweron_vram_183")]
    [TestCase("poweron_vram_184")]
    [TestCase("ppu_sprite0_scx0_a")]
    [TestCase("ppu_sprite0_scx0_b")]
    [TestCase("ppu_sprite0_scx1_a")]
    [TestCase("ppu_sprite0_scx1_b")]
    [TestCase("ppu_sprite0_scx2_a")]
    [TestCase("ppu_sprite0_scx2_b")]
    [TestCase("ppu_sprite0_scx3_a")]
    [TestCase("ppu_sprite0_scx3_b")]
    [TestCase("ppu_sprite0_scx4_a")]
    [TestCase("ppu_sprite0_scx4_b")]
    [TestCase("ppu_sprite0_scx5_a")]
    [TestCase("ppu_sprite0_scx5_b")]
    [TestCase("ppu_sprite0_scx6_a")]
    [TestCase("ppu_sprite0_scx6_b")]
    [TestCase("ppu_sprite0_scx7_a")]
    [TestCase("ppu_sprite0_scx7_b")]
    [TestCase("sprite4_0_a")]
    [TestCase("sprite4_0_b")]
    [TestCase("sprite4_1_a")]
    [TestCase("sprite4_1_b")]
    [TestCase("sprite4_2_a")]
    [TestCase("sprite4_2_b")]
    [TestCase("sprite4_3_a")]
    [TestCase("sprite4_3_b")]
    [TestCase("sprite4_4_a")]
    [TestCase("sprite4_4_b")]
    [TestCase("sprite4_5_a")]
    [TestCase("sprite4_5_b")]
    [TestCase("sprite4_6_a")]
    [TestCase("sprite4_6_b")]
    [TestCase("sprite4_7_a")]
    [TestCase("sprite4_7_b")]
    [TestCase("sprite_0_a")]
    [TestCase("sprite_0_b")]
    [TestCase("sprite_1_a")]
    [TestCase("sprite_1_b")]
    [TestCase("stat_write_glitch_l0_a")]
    [TestCase("stat_write_glitch_l0_b")]
    [TestCase("stat_write_glitch_l143_b")]
    [TestCase("stat_write_glitch_l143_c")]
    [TestCase("stat_write_glitch_l143_d")]
    [TestCase("stat_write_glitch_l154_a")]
    [TestCase("stat_write_glitch_l154_b")]
    [TestCase("stat_write_glitch_l154_d")]
    [TestCase("stat_write_glitch_l1_b")]
    [TestCase("stat_write_glitch_l1_c")]
    [TestCase("timer_tima_phase_a")]
    [TestCase("timer_tima_phase_b")]
    [TestCase("timer_tima_phase_c")]
    [TestCase("timer_tima_phase_d")]
    [TestCase("timer_tima_phase_e")]
    [TestCase("timer_tima_phase_f")]
    [TestCase("timer_tima_phase_g")]
    [TestCase("timer_tima_phase_h")]
    [TestCase("timer_tima_phase_i")]
    [TestCase("timer_tima_phase_j")]
    [TestCase("vblank2_int_halt_b")]
    [TestCase("vblank2_int_if_a")]
    [TestCase("vblank2_int_if_c")]
    [TestCase("vblank2_int_inc_sled")]
    [TestCase("vblank2_int_nops_b")]
    [TestCase("vblank_int_halt_b")]
    [TestCase("vblank_int_if_a")]
    [TestCase("vblank_int_if_c")]
    [TestCase("vblank_int_inc_sled")]
    [TestCase("vblank_int_nops_b")]
    [TestCase("vram_read_l0_a")]
    [TestCase("vram_read_l0_c")]
    [TestCase("vram_write_l0_a")]
    [TestCase("vram_write_l0_c")]
    [TestCase("vram_write_l1_a")]
    [TestCase("win0_a")]
    [TestCase("win0_b")]
    [TestCase("win0_scx3_a")]
    [TestCase("win0_scx3_b")]
    [TestCase("win10_a")]
    [TestCase("win10_b")]
    [TestCase("win10_scx3_a")]
    [TestCase("win10_scx3_b")]
    [TestCase("win11_a")]
    [TestCase("win11_b")]
    [TestCase("win12_a")]
    [TestCase("win12_b")]
    [TestCase("win13_a")]
    [TestCase("win13_b")]
    [TestCase("win14_a")]
    [TestCase("win14_b")]
    [TestCase("win15_a")]
    [TestCase("win15_b")]
    [TestCase("win1_a")]
    [TestCase("win1_b")]
    [TestCase("win2_a")]
    [TestCase("win2_b")]
    [TestCase("win3_a")]
    [TestCase("win3_b")]
    [TestCase("win4_a")]
    [TestCase("win4_b")]
    [TestCase("win5_a")]
    [TestCase("win5_b")]
    [TestCase("win6_a")]
    [TestCase("win6_b")]
    [TestCase("win7_a")]
    [TestCase("win7_b")]
    [TestCase("win8_a")]
    [TestCase("win8_b")]
    [TestCase("win9_a")]
    [TestCase("win9_b")]
    [TestCase("dma_basic")]
    public void Test(string fileName)
    {
        var path = @"rom\gbmicrotest";
        var filePath = Path.Combine(path, fileName + ".gb");

        RunSample(filePath);
    }

    [Test]
    public void DMABusAccess()
    {
        // This legacy ROM displays sprites and loops forever; FF80 contains code,
        // not the result flags used by the newer microtests.
        var rom = File.ReadAllBytes(@"rom\gbmicrotest\400-dma.gb");
        using var core = TestHelpers.NewCore(rom, new TestRenderDevice());
        while (core.CPU.PC != 0x0190 && core.Time() < 2 * 4_194_304)
            core.Step();

        Assert.That(core.CPU.PC, Is.EqualTo(0x0190), "400-dma did not reach its terminal loop.");
        core.Memory[0xff40] = 0; // Unlock OAM for inspection.
        for (int i = 0; i < 160; i++)
            Assert.That(core.Memory[(ushort)(0xfe00 + i)], Is.EqualTo(rom[0x0200 + i]), $"OAM byte {i:X2}");
    }

    private static void RunSample(string rom)
    {
        string? name = Path.GetFileNameWithoutExtension(rom);
        var render = new TestRenderDevice();
        using var core = TestHelpers.NewCore(File.ReadAllBytes(rom), name, render);
        int frames = 0;
        bool finished = false;
        render.FramePushed += (_, _) =>
        {
            frames++;
        };
        long deadline = 2 * 4_194_304;
        while (!finished && core.Time() < deadline)
        {
            //check every 10000 cycles if the test has finished
            var time = core.Time();
            if (time > 100000 && time % 10000 == 0)
            {
                var result = core.Memory[0xff80];
                var expected = core.Memory[0xff81];
                var finalValue = core.Memory[0xff82];
                if (finalValue is 0x01 or 0xff)
                {
                    finished = true;
                    if (expected != 0xff)
                        Assert.That(result, Is.EqualTo(expected), $"Test {name} failed: expected {expected:X2}, got {result:X2}");
                    return;
                }
            }
            core.Step();
        }

        Assert.Fail($"Test {name} did not finish within the time limit.");
    }
}