<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net11.0</TargetFrameworks>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
	</PropertyGroup>

	<ItemGroup>
		<Content Include="rom\**">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="coverlet.collector" Version="6.0.4">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="nunit" Version="4.3.2" />
		<PackageReference Include="NUnit3TestAdapter" Version="5.0.0" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
		<PackageReference Include="Magick.NET-Q8-x64" Version="14.5.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\emulator\emulator.csproj" />
		<ProjectReference Include="..\WAV\WAV.csproj" />
	</ItemGroup>

</Project>
