<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net11.0-windows10.0.19041.0</TargetFramework>
		<TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
		<UseWinUI>true</UseWinUI>
		<WindowsPackageType>None</WindowsPackageType>
		<WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
		<Platforms>x64</Platforms>
		<PlatformTarget>x64</PlatformTarget>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<AssemblyName>WPFFrontend</AssemblyName>
		<RootNamespace>WPFFrontend</RootNamespace>
		<Nullable>enable</Nullable>
		<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="Commands\**" />
		<EmbeddedResource Remove="Commands\**" />
		<None Remove="Commands\**" />
		<Page Remove="Commands\**" />
	</ItemGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.WindowsAppSDK" Version="2.5.1" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
		<PackageReference Include="NAudio" Version="3.1.1-preview.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\emulator\emulator.csproj" />
		<ProjectReference Include="..\Xinput\J2i.Net.XInputWrapper.csproj" />
		<Content Include="..\emulator\bootrom\DMG_ROM_BOOT.bin" Link="bootrom\DMG_ROM_BOOT.bin" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
	</ItemGroup>

</Project>
